modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Quick%20Right-Click"
logoFile="icon.png"

[[mods]]
modId="quickrightclick"
version="1.0"
displayName="Quick Right-Click"
displayURL="https://curseforge.com/minecraft/mc-mods/quick-right-click"
authors="Rick South"
description='''Adds the functionality to right-click items in the air to access them quickly without placing them. Works for beds, cartography tables, crafting tables, ender chests, grindstones, shulker boxes, smithing tables and stonecutters.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.quickrightclick]]
    modId="collective"
    mandatory=true
    versionRange="[6.62,)"
    ordering="NONE"
    side="BOTH"