modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Quick%20Right-Click"
logoFile="icon.png"

[[mods]]
modId="quickrightclick"
version="1.4"
displayName="Quick Right-Click"
displayURL="https://serilum.com/mod/quick-right-click"
authors="Rick South"
description='''Adds the functionality to right-click items in the air to access them quickly without placing them. Works for beds, cartography tables, crafting tables, ender chests, grindstones, shulker boxes, smithing tables and stonecutters.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.quickrightclick]]
    modId="collective"
    type="required"
    versionRange="[7.52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quickrightclick]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "quickrightclick.mixins.json"